title: Docs
description: Desc

url: "https://yab-org.github.io"
baseurl: "/docs"
permalink: pretty

theme: just-the-docs
color_scheme: dark
heading_anchors: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      has_toc: false

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true
